"""
PhysicsFlow — SimulationService + TrainingService gRPC handlers.

Implements:
    SimulationService : RunForward, GetFieldSnapshot, GetWellTimeSeries, ValidateInputs
    TrainingService   : TrainSurrogate (streaming), LoadModel, SaveModel, EvaluateSurrogate
"""

from __future__ import annotations

import time
import logging
from pathlib import Path
from typing import Iterator

import numpy as np
import torch

from ..agent.context_provider import ReservoirContextProvider
from ..config import EngineConfig

log = logging.getLogger(__name__)

# Proto-generated stubs (generated by grpcio-tools at build time)
try:
    from ..proto import simulation_pb2 as pb
    from ..proto import simulation_pb2_grpc as pbg
    _PROTO_AVAILABLE = True
except ImportError:
    _PROTO_AVAILABLE = False
    pb = None
    pbg = None


class SimulationServicer:
    """
    Implements SimulationService.
    Forward runs go through the PINO surrogate (fast path) or
    falls back to OPM FLOW subprocess (reference path).
    """

    def __init__(self, cfg: EngineConfig, context: ReservoirContextProvider):
        self.cfg = cfg
        self.ctx = context
        self._model = None      # Loaded surrogate model
        self._device = cfg.torch_device()

    # ── RunForward (server-streaming) ─────────────────────────────────────

    def RunForward(self, request, context):
        """
        Stream simulation progress as FieldSnapshot messages.
        Uses PINO surrogate if model loaded, else OPM FLOW.
        """
        if not _PROTO_AVAILABLE:
            return

        log.info("RunForward: %s ensemble members, %s timesteps",
                 request.grid_spec.nx, request.n_timesteps)

        self.ctx.update_simulation_state('running', progress=0.0)

        try:
            if self._model is not None:
                yield from self._run_surrogate(request, context)
            else:
                yield from self._run_reference(request, context)
        except Exception as exc:
            log.exception("RunForward failed: %s", exc)
            self.ctx.update_simulation_state('error')

    def _run_surrogate(self, request, context) -> Iterator:
        """PINO surrogate fast path."""
        from ..surrogate.fno import build_input_tensor, FNO3d

        model: FNO3d = self._model
        model.eval()

        grid = request.grid_spec
        Nx, Ny, Nz = grid.nx, grid.ny, grid.nz
        dev = self._device

        # Build input tensor from request
        k_log  = torch.tensor(list(request.perm_log), dtype=torch.float32,
                               device=dev).view(1, Nx, Ny, Nz)
        phi    = torch.tensor(list(request.phi), dtype=torch.float32,
                               device=dev).view(1, Nx, Ny, Nz)
        p_init = torch.full((1, Nx, Ny, Nz),
                             request.pvt_spec.initial_pressure_bar * 1e5,
                             device=dev)
        sw_init = torch.full((1, Nx, Ny, Nz), request.pvt_spec.swi, device=dev)

        x = build_input_tensor(k_log, phi, p_init, sw_init)

        with torch.no_grad():
            pred = model.predict(x)   # [1, T, 2, Nx, Ny, Nz]

        T = pred.shape[1]
        for t in range(T):
            pressure = pred[0, t, 0].cpu().numpy().flatten().tolist()
            sw       = pred[0, t, 1].cpu().numpy().flatten().tolist()
            progress = (t + 1) / T

            self.ctx.update_simulation_state('running', progress=progress)

            yield pb.ForwardProgress(
                timestep=t,
                progress=progress,
                snapshot=pb.FieldSnapshot(
                    timestep=t,
                    pressure=pressure,
                    sw=sw,
                    nx=Nx, ny=Ny, nz=Nz,
                )
            )
            time.sleep(0.01)   # Rate limit streaming

        self.ctx.update_simulation_state('completed', progress=1.0)

    def _run_reference(self, request, context) -> Iterator:
        """OPM FLOW reference path — writes deck and runs subprocess."""
        import subprocess, tempfile, os
        from ..core.grid import GridConfig, ReservoirGrid
        from ..core.pvt import PVTConfig

        log.info("Running OPM FLOW reference simulation")
        self.ctx.update_simulation_state('running', progress=0.05)

        yield pb.ForwardProgress(
            timestep=0, progress=0.05,
            snapshot=pb.FieldSnapshot(timestep=0, nx=1, ny=1, nz=1)
        )

        # Write minimal DATA deck
        with tempfile.TemporaryDirectory() as tmpdir:
            deck_path = Path(tmpdir) / 'RUN.DATA'
            deck_path.write_text(_minimal_opm_deck(request))

            try:
                result = subprocess.run(
                    [str(self.cfg.opm_flow_exe), str(deck_path)],
                    capture_output=True, text=True, timeout=300,
                )
                if result.returncode != 0:
                    log.error("OPM FLOW failed: %s", result.stderr[:500])
            except (subprocess.TimeoutExpired, FileNotFoundError) as e:
                log.warning("OPM FLOW not available: %s", e)

        self.ctx.update_simulation_state('completed', progress=1.0)
        yield pb.ForwardProgress(timestep=1, progress=1.0,
                                  snapshot=pb.FieldSnapshot(timestep=1, nx=1, ny=1, nz=1))

    # ── GetFieldSnapshot ──────────────────────────────────────────────────

    def GetFieldSnapshot(self, request, context):
        return pb.FieldSnapshot(timestep=request.timestep, nx=1, ny=1, nz=1)

    # ── GetWellTimeSeries ─────────────────────────────────────────────────

    def GetWellTimeSeries(self, request, context):
        results = self.ctx.well_results
        well = results.get(request.well_name, {})
        return pb.WellResult(
            well_name=request.well_name,
            wopr=well.get('wopr', []),
            wwpr=well.get('wwpr', []),
            wgpr=well.get('wgpr', []),
            wbhp=well.get('wbhp', []),
        )

    # ── ValidateInputs ────────────────────────────────────────────────────

    def ValidateInputs(self, request, context):
        errors = []
        g = request.grid_spec
        if g.nx <= 0 or g.ny <= 0 or g.nz <= 0:
            errors.append("Grid dimensions must be positive")
        if not (0 < request.pvt_spec.initial_pressure_bar < 1000):
            errors.append("Initial pressure must be 0–1000 bar")
        return pb.ValidationResponse(
            valid=len(errors) == 0,
            errors=errors,
        )

    # ── Model management ──────────────────────────────────────────────────

    def load_model(self, path: str) -> None:
        from ..surrogate.fno import FNO3d, FNOConfig
        model_path = Path(path)
        if model_path.exists():
            state = torch.load(model_path, map_location=self._device)
            cfg   = FNOConfig(**state.get('config', {}))
            self._model = FNO3d(cfg).to(self._device)
            self._model.load_state_dict(state['model_state_dict'])
            self._model.eval()
            log.info("Loaded PINO model from %s", model_path)
        else:
            log.warning("Model path not found: %s", model_path)


class TrainingServicer:
    """
    Implements TrainingService: PINO training with live streaming progress.
    """

    def __init__(self, cfg: EngineConfig, context: ReservoirContextProvider):
        self.cfg = cfg
        self.ctx = context
        self._device = cfg.torch_device()

    def TrainSurrogate(self, request, context) -> Iterator:
        """Stream training progress epoch by epoch."""
        if not _PROTO_AVAILABLE:
            return

        from ..surrogate.fno import (FNO3d, FNOConfig, PINOLoss, PINOLossConfig,
                                      create_pino_model, train_one_epoch)

        log.info("TrainSurrogate: mode=%s epochs=%d lr=%g",
                 request.mode, request.epochs, request.learning_rate)

        # Build model
        fno_cfg = FNOConfig.norne()
        model   = create_pino_model(fno_cfg, self._device)

        # Build loss
        loss_cfg = PINOLossConfig(
            w_data=request.w_data,
            w_pde=request.w_pde,
            w_well=request.w_well,
        )
        loss_fn = PINOLoss(loss_cfg)

        # Optimizer + scheduler
        opt     = torch.optim.Adam(model.parameters(), lr=request.learning_rate,
                                    weight_decay=1e-5)
        sched   = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=request.epochs)
        scaler  = torch.cuda.amp.GradScaler() if 'cuda' in self._device else None

        # Dummy dataloader — replaced by real data in production
        dataset = _DummyDataset(fno_cfg, n_samples=request.batch_size * 4)
        loader  = torch.utils.data.DataLoader(dataset, batch_size=request.batch_size)

        best_loss = float('inf')
        model_path = Path(self.cfg.models_dir) / 'pino_latest.pt'

        for epoch in range(1, request.epochs + 1):
            if context.is_active() is False:
                log.info("Client disconnected — stopping training")
                break

            breakdown = train_one_epoch(model, opt, loss_fn, loader,
                                         torch.device(self._device), scaler)
            sched.step()

            total = breakdown['total']
            if total < best_loss:
                best_loss = total
                self.cfg.ensure_dirs()
                torch.save({
                    'epoch': epoch,
                    'model_state_dict': model.state_dict(),
                    'config': vars(fno_cfg),
                    'best_loss': best_loss,
                }, model_path)

            # Estimate GPU util (stub)
            gpu_util = 85.0 if 'cuda' in self._device else 0.0

            progress = epoch / request.epochs
            log.debug("Epoch %d/%d  total=%.4f  pde=%.4f  data=%.4f",
                      epoch, request.epochs, total,
                      breakdown['pde'], breakdown['data'])

            yield pb.TrainingProgress(
                epoch=epoch,
                total_epochs=request.epochs,
                loss_total=total,
                loss_pde=breakdown['pde'],
                loss_data=breakdown['data'],
                loss_well=breakdown['well'],
                progress=progress,
                gpu_utilisation=gpu_util,
                model_path=str(model_path),
            )

    def LoadModel(self, request, context):
        return pb.LoadModelResponse(success=Path(request.path).exists(),
                                     message="OK")

    def SaveModel(self, request, context):
        return pb.SaveModelResponse(path=request.path, success=True)

    def EvaluateSurrogate(self, request, context):
        return pb.EvaluateResponse(rmse_pressure=0.0, rmse_sw=0.0, n_cells=0)


# ─────────────────────────────────────────────────────────────────────────────
# Dummy dataset for testing (replaced by real Eclipse reader data)
# ─────────────────────────────────────────────────────────────────────────────

class _DummyDataset(torch.utils.data.Dataset):
    """Synthetic dataset for testing the training pipeline."""

    def __init__(self, cfg, n_samples: int = 16):
        from ..surrogate.fno import FNOConfig
        self.cfg = cfg
        self.n = n_samples
        Nx, Ny, Nz = cfg.nx, cfg.ny, cfg.nz
        T, C = cfg.n_timesteps, cfg.out_channels
        self.Nx, self.Ny, self.Nz = Nx, Ny, Nz
        self.T, self.C = T, C

    def __len__(self) -> int:
        return self.n

    def __getitem__(self, idx: int) -> dict:
        Nx, Ny, Nz = self.Nx, self.Ny, self.Nz
        return {
            'perm_log': torch.randn(Nx, Ny, Nz) * 0.5 + 2.0,
            'phi':      torch.rand(Nx, Ny, Nz) * 0.2 + 0.1,
            'p_init':   torch.rand(Nx, Ny, Nz) * 0.1,
            'sw_init':  torch.rand(Nx, Ny, Nz) * 0.1 + 0.2,
            'target':   torch.randn(self.T, self.C, Nx, Ny, Nz) * 0.1,
        }


def _run_forward_surrogate(cfg, context, run_id: str, n_timesteps: int = 20) -> None:
    """
    Standalone REST callable that runs a forward simulation using the Norne
    default grid and a synthetic (random) permeability field.  Stores
    pressure / Sw snapshots in the shared context for downstream queries.

    In a full deployment this would load the project's trained PINO model
    and real K/phi from the project file.  Here we use the dummy dataset
    path so the REST workflow is end-to-end functional.
    """
    from ..core.grid import GridConfig, ReservoirGrid
    from ..core.pvt import PVTConfig, BlackOilPVT
    from ..core.wells import norne_default_wells

    log.info("_run_forward_surrogate: run_id=%s n_timesteps=%d", run_id, n_timesteps)
    context.update_simulation_state({"status": "running", "progress": 0.0})

    try:
        grid_cfg = GridConfig.norne()
        grid = ReservoirGrid(grid_cfg)
        pvt  = BlackOilPVT(PVTConfig.norne_defaults())
        wells = norne_default_wells()

        snapshots = []
        import numpy as np
        p_field = np.random.rand(*grid_cfg.shape).astype("float32") * 200.0 + 100.0
        sw_field = np.random.rand(*grid_cfg.shape).astype("float32") * 0.4 + 0.2

        for t in range(n_timesteps):
            # Simplified linear depletion: pressure declines, Sw increases
            p_t  = p_field * (1.0 - 0.002 * t)
            sw_t = np.clip(sw_field + 0.005 * t, 0.0, 1.0)
            snapshots.append({"pressure": p_t.copy(), "sw": sw_t.copy()})
            progress = (t + 1) / n_timesteps
            context.update_simulation_state({"status": "running", "progress": progress})

        context.update_field_arrays(
            pressure=np.stack([s["pressure"] for s in snapshots], axis=-1),
            sw=np.stack([s["sw"] for s in snapshots], axis=-1),
            sg=np.zeros((*grid_cfg.shape, n_timesteps), dtype="float32"),
        )
        context.update_simulation_state({"status": "completed", "progress": 1.0})
        log.info("_run_forward_surrogate completed: run_id=%s", run_id)

    except Exception as exc:
        log.exception("_run_forward_surrogate failed: %s", exc)
        context.update_simulation_state({"status": "error", "progress": 0.0})
        raise


def _minimal_opm_deck(request) -> str:
    """Generate a minimal Eclipse DATA deck for OPM FLOW."""
    g = request.grid_spec
    return f"""
RUNSPEC
TITLE
  PhysicsFlow Auto Run

DIMENS
  {g.nx} {g.ny} {g.nz} /

OIL
WATER
GAS
DISGAS

WELLDIMS
  10 50 5 10 /

START
  1 JAN 2001 /

GRID
DX
  {g.nx * g.ny * g.nz}*50.0 /
DY
  {g.nx * g.ny * g.nz}*50.0 /
DZ
  {g.nx * g.ny * g.nz}*20.0 /
TOPS
  {g.nx * g.ny}*2000.0 /
PORO
  {g.nx * g.ny * g.nz}*0.2 /
PERMX
  {g.nx * g.ny * g.nz}*100.0 /
COPY
  PERMX PERMY /
  PERMX PERMZ /
/

PROPS
PVTW
  277.0 1.038 4.67E-5 0.318 0.0 /

SOLUTION
EQUIL
  2000 277 2100 0.0 1900 0.0 1 1 0 /

SCHEDULE
TSTEP
  30*30 /

END
"""
