# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.62.0'
GRPC_VERSION = grpc.__version__


class AgentServiceStub(object):
    """─── AI Reservoir Assistant Service ──────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/physicsflow.AgentService/Chat',
                request_serializer=agent__pb2.ChatRequest.SerializeToString,
                response_deserializer=agent__pb2.ChatToken.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/physicsflow.AgentService/ListModels',
                request_serializer=agent__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=agent__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.SetModel = channel.unary_unary(
                '/physicsflow.AgentService/SetModel',
                request_serializer=agent__pb2.SetModelRequest.SerializeToString,
                response_deserializer=agent__pb2.SetModelResponse.FromString,
                _registered_method=True)
        self.ClearHistory = channel.unary_unary(
                '/physicsflow.AgentService/ClearHistory',
                request_serializer=agent__pb2.ClearHistoryRequest.SerializeToString,
                response_deserializer=agent__pb2.ClearHistoryResponse.FromString,
                _registered_method=True)
        self.GetToolLog = channel.unary_unary(
                '/physicsflow.AgentService/GetToolLog',
                request_serializer=agent__pb2.ToolLogRequest.SerializeToString,
                response_deserializer=agent__pb2.ToolLogResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """─── AI Reservoir Assistant Service ──────────────────────────────────────────

    """

    def Chat(self, request, context):
        """Send a chat message; stream back token-by-token response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List available Ollama models on this machine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetModel(self, request, context):
        """Set the active LLM model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearHistory(self, request, context):
        """Clear conversation history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolLog(self, request, context):
        """Get agent tool execution log (what tools it called)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=agent__pb2.ChatRequest.FromString,
                    response_serializer=agent__pb2.ChatToken.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=agent__pb2.ListModelsRequest.FromString,
                    response_serializer=agent__pb2.ListModelsResponse.SerializeToString,
            ),
            'SetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModel,
                    request_deserializer=agent__pb2.SetModelRequest.FromString,
                    response_serializer=agent__pb2.SetModelResponse.SerializeToString,
            ),
            'ClearHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearHistory,
                    request_deserializer=agent__pb2.ClearHistoryRequest.FromString,
                    response_serializer=agent__pb2.ClearHistoryResponse.SerializeToString,
            ),
            'GetToolLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolLog,
                    request_deserializer=agent__pb2.ToolLogRequest.FromString,
                    response_serializer=agent__pb2.ToolLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physicsflow.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physicsflow.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """─── AI Reservoir Assistant Service ──────────────────────────────────────────

    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/physicsflow.AgentService/Chat',
            agent__pb2.ChatRequest.SerializeToString,
            agent__pb2.ChatToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.AgentService/ListModels',
            agent__pb2.ListModelsRequest.SerializeToString,
            agent__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.AgentService/SetModel',
            agent__pb2.SetModelRequest.SerializeToString,
            agent__pb2.SetModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.AgentService/ClearHistory',
            agent__pb2.ClearHistoryRequest.SerializeToString,
            agent__pb2.ClearHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToolLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.AgentService/GetToolLog',
            agent__pb2.ToolLogRequest.SerializeToString,
            agent__pb2.ToolLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
