# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import history_matching_pb2 as history__matching__pb2

GRPC_GENERATED_VERSION = '1.62.0'
GRPC_VERSION = grpc.__version__


class HistoryMatchingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunHistoryMatch = channel.unary_stream(
                '/physicsflow.HistoryMatchingService/RunHistoryMatch',
                request_serializer=history__matching__pb2.HistoryMatchRequest.SerializeToString,
                response_deserializer=history__matching__pb2.HMProgress.FromString,
                _registered_method=True)
        self.GetEnsembleStats = channel.unary_unary(
                '/physicsflow.HistoryMatchingService/GetEnsembleStats',
                request_serializer=history__matching__pb2.EnsembleStatsRequest.SerializeToString,
                response_deserializer=history__matching__pb2.EnsembleStatsResponse.FromString,
                _registered_method=True)
        self.GetDataMismatch = channel.unary_unary(
                '/physicsflow.HistoryMatchingService/GetDataMismatch',
                request_serializer=history__matching__pb2.DataMismatchRequest.SerializeToString,
                response_deserializer=history__matching__pb2.DataMismatchResponse.FromString,
                _registered_method=True)
        self.GetParameterEnsemble = channel.unary_unary(
                '/physicsflow.HistoryMatchingService/GetParameterEnsemble',
                request_serializer=history__matching__pb2.ParameterRequest.SerializeToString,
                response_deserializer=history__matching__pb2.ParameterResponse.FromString,
                _registered_method=True)
        self.StopHistoryMatch = channel.unary_unary(
                '/physicsflow.HistoryMatchingService/StopHistoryMatch',
                request_serializer=history__matching__pb2.StopRequest.SerializeToString,
                response_deserializer=history__matching__pb2.StopResponse.FromString,
                _registered_method=True)


class HistoryMatchingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunHistoryMatch(self, request, context):
        """Run full αREKI history matching workflow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnsembleStats(self, request, context):
        """Get current ensemble statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataMismatch(self, request, context):
        """Get per-well data mismatch breakdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParameterEnsemble(self, request, context):
        """Get updated parameter fields (P10/P50/P90)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopHistoryMatch(self, request, context):
        """Stop running history match
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HistoryMatchingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunHistoryMatch': grpc.unary_stream_rpc_method_handler(
                    servicer.RunHistoryMatch,
                    request_deserializer=history__matching__pb2.HistoryMatchRequest.FromString,
                    response_serializer=history__matching__pb2.HMProgress.SerializeToString,
            ),
            'GetEnsembleStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnsembleStats,
                    request_deserializer=history__matching__pb2.EnsembleStatsRequest.FromString,
                    response_serializer=history__matching__pb2.EnsembleStatsResponse.SerializeToString,
            ),
            'GetDataMismatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataMismatch,
                    request_deserializer=history__matching__pb2.DataMismatchRequest.FromString,
                    response_serializer=history__matching__pb2.DataMismatchResponse.SerializeToString,
            ),
            'GetParameterEnsemble': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameterEnsemble,
                    request_deserializer=history__matching__pb2.ParameterRequest.FromString,
                    response_serializer=history__matching__pb2.ParameterResponse.SerializeToString,
            ),
            'StopHistoryMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.StopHistoryMatch,
                    request_deserializer=history__matching__pb2.StopRequest.FromString,
                    response_serializer=history__matching__pb2.StopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physicsflow.HistoryMatchingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physicsflow.HistoryMatchingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HistoryMatchingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunHistoryMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/physicsflow.HistoryMatchingService/RunHistoryMatch',
            history__matching__pb2.HistoryMatchRequest.SerializeToString,
            history__matching__pb2.HMProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnsembleStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.HistoryMatchingService/GetEnsembleStats',
            history__matching__pb2.EnsembleStatsRequest.SerializeToString,
            history__matching__pb2.EnsembleStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDataMismatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.HistoryMatchingService/GetDataMismatch',
            history__matching__pb2.DataMismatchRequest.SerializeToString,
            history__matching__pb2.DataMismatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParameterEnsemble(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.HistoryMatchingService/GetParameterEnsemble',
            history__matching__pb2.ParameterRequest.SerializeToString,
            history__matching__pb2.ParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopHistoryMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.HistoryMatchingService/StopHistoryMatch',
            history__matching__pb2.StopRequest.SerializeToString,
            history__matching__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
