# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import simulation_pb2 as simulation__pb2

GRPC_GENERATED_VERSION = '1.62.0'
GRPC_VERSION = grpc.__version__


class SimulationServiceStub(object):
    """─── Simulation Service ───────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunForward = channel.unary_stream(
                '/physicsflow.SimulationService/RunForward',
                request_serializer=simulation__pb2.ForwardRequest.SerializeToString,
                response_deserializer=simulation__pb2.ForwardProgress.FromString,
                _registered_method=True)
        self.GetFieldSnapshot = channel.unary_unary(
                '/physicsflow.SimulationService/GetFieldSnapshot',
                request_serializer=simulation__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=simulation__pb2.FieldSnapshot.FromString,
                _registered_method=True)
        self.GetWellTimeSeries = channel.unary_unary(
                '/physicsflow.SimulationService/GetWellTimeSeries',
                request_serializer=simulation__pb2.WellTimeSeriesRequest.SerializeToString,
                response_deserializer=simulation__pb2.WellTimeSeriesResponse.FromString,
                _registered_method=True)
        self.ValidateInputs = channel.unary_unary(
                '/physicsflow.SimulationService/ValidateInputs',
                request_serializer=simulation__pb2.ForwardRequest.SerializeToString,
                response_deserializer=simulation__pb2.ValidationResult.FromString,
                _registered_method=True)


class SimulationServiceServicer(object):
    """─── Simulation Service ───────────────────────────────────────────────────────

    """

    def RunForward(self, request, context):
        """Run single forward simulation (PINO surrogate)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFieldSnapshot(self, request, context):
        """Get 3D field snapshot at a given time step
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWellTimeSeries(self, request, context):
        """Get all well production time series
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateInputs(self, request, context):
        """Validate inputs before running
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunForward': grpc.unary_stream_rpc_method_handler(
                    servicer.RunForward,
                    request_deserializer=simulation__pb2.ForwardRequest.FromString,
                    response_serializer=simulation__pb2.ForwardProgress.SerializeToString,
            ),
            'GetFieldSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFieldSnapshot,
                    request_deserializer=simulation__pb2.SnapshotRequest.FromString,
                    response_serializer=simulation__pb2.FieldSnapshot.SerializeToString,
            ),
            'GetWellTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWellTimeSeries,
                    request_deserializer=simulation__pb2.WellTimeSeriesRequest.FromString,
                    response_serializer=simulation__pb2.WellTimeSeriesResponse.SerializeToString,
            ),
            'ValidateInputs': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateInputs,
                    request_deserializer=simulation__pb2.ForwardRequest.FromString,
                    response_serializer=simulation__pb2.ValidationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physicsflow.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physicsflow.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService(object):
    """─── Simulation Service ───────────────────────────────────────────────────────

    """

    @staticmethod
    def RunForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/physicsflow.SimulationService/RunForward',
            simulation__pb2.ForwardRequest.SerializeToString,
            simulation__pb2.ForwardProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFieldSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.SimulationService/GetFieldSnapshot',
            simulation__pb2.SnapshotRequest.SerializeToString,
            simulation__pb2.FieldSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWellTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.SimulationService/GetWellTimeSeries',
            simulation__pb2.WellTimeSeriesRequest.SerializeToString,
            simulation__pb2.WellTimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateInputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.SimulationService/ValidateInputs',
            simulation__pb2.ForwardRequest.SerializeToString,
            simulation__pb2.ValidationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrainingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainSurrogate = channel.unary_stream(
                '/physicsflow.TrainingService/TrainSurrogate',
                request_serializer=simulation__pb2.TrainingRequest.SerializeToString,
                response_deserializer=simulation__pb2.TrainingProgress.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/physicsflow.TrainingService/LoadModel',
                request_serializer=simulation__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=simulation__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.SaveModel = channel.unary_unary(
                '/physicsflow.TrainingService/SaveModel',
                request_serializer=simulation__pb2.SaveModelRequest.SerializeToString,
                response_deserializer=simulation__pb2.SaveModelResponse.FromString,
                _registered_method=True)
        self.EvaluateSurrogate = channel.unary_unary(
                '/physicsflow.TrainingService/EvaluateSurrogate',
                request_serializer=simulation__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=simulation__pb2.EvaluateResponse.FromString,
                _registered_method=True)


class TrainingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainSurrogate(self, request, context):
        """Train PINO surrogate (PyTorch)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Load pre-trained model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveModel(self, request, context):
        """Save current model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateSurrogate(self, request, context):
        """Evaluate surrogate accuracy on held-out set
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainSurrogate': grpc.unary_stream_rpc_method_handler(
                    servicer.TrainSurrogate,
                    request_deserializer=simulation__pb2.TrainingRequest.FromString,
                    response_serializer=simulation__pb2.TrainingProgress.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=simulation__pb2.LoadModelRequest.FromString,
                    response_serializer=simulation__pb2.LoadModelResponse.SerializeToString,
            ),
            'SaveModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveModel,
                    request_deserializer=simulation__pb2.SaveModelRequest.FromString,
                    response_serializer=simulation__pb2.SaveModelResponse.SerializeToString,
            ),
            'EvaluateSurrogate': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateSurrogate,
                    request_deserializer=simulation__pb2.EvaluateRequest.FromString,
                    response_serializer=simulation__pb2.EvaluateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'physicsflow.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('physicsflow.TrainingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainSurrogate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/physicsflow.TrainingService/TrainSurrogate',
            simulation__pb2.TrainingRequest.SerializeToString,
            simulation__pb2.TrainingProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.TrainingService/LoadModel',
            simulation__pb2.LoadModelRequest.SerializeToString,
            simulation__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.TrainingService/SaveModel',
            simulation__pb2.SaveModelRequest.SerializeToString,
            simulation__pb2.SaveModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateSurrogate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/physicsflow.TrainingService/EvaluateSurrogate',
            simulation__pb2.EvaluateRequest.SerializeToString,
            simulation__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
